export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export interface Database { public: { Tables: {
  trips: { Row: { id: string; user_id: string; title: string; description: string | null; cover_image_url: string | null; gallery_url:string|null; start_date: string; end_date: string; visibility: 'private'|'friends'|'public'; route_geometry: Json | null; created_at: string; updated_at: string }; Insert: { id?: string; user_id?: string; title: string; description?: string|null; cover_image_url?: string|null;gallery_url?:string|null; start_date: string; end_date: string; visibility?: 'private'|'friends'|'public'; route_geometry?: Json|null }; Update: Partial<Database['public']['Tables']['trips']['Insert']> };
  trip_stops: { Row: { id: string; trip_id: string; memory_id: string|null; position: number; title: string|null; latitude: number|null; longitude: number|null; city: string|null; country: string|null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['trip_stops']['Row'],'id'|'created_at'|'updated_at'> & { id?: string }; Update: Partial<Database['public']['Tables']['trip_stops']['Insert']> };
  trip_participants: { Row: { trip_id: string; user_id: string; created_at: string }; Insert: { trip_id: string; user_id: string }; Update: never };
  trip_wines: { Row: { trip_id: string; wine_id: string; created_at: string }; Insert: { trip_id: string; wine_id: string }; Update: never };
  trip_photos: { Row: { id: string; trip_id: string; storage_path: string; caption: string|null; position: number; created_at: string }; Insert: { id?: string; trip_id: string; storage_path: string; caption?: string|null; position: number }; Update: Partial<Database['public']['Tables']['trip_photos']['Insert']> };
  user_wines: { Row: { id:string;user_id:string;wine_id:string;favorite:boolean;rating:number|null;tasting_notes:string|null;date_tasted:string|null;purchase_price:number|null;purchase_location:string|null;shop:string|null;created_at:string;updated_at:string }; Insert: {id?:string;user_id:string;wine_id:string;favorite?:boolean;rating?:number|null;tasting_notes?:string|null;date_tasted?:string|null;purchase_price?:number|null;purchase_location?:string|null;shop?:string|null}; Update: Partial<Database['public']['Tables']['user_wines']['Insert']> };
  user_library_items: { Row: {id:string;user_id:string;library_item_id:string;saved:boolean;favorite:boolean;reading_progress:number;personal_notes:string|null;completed:boolean;date_added:string}; Insert:{id?:string;user_id:string;library_item_id:string;saved?:boolean;favorite?:boolean;reading_progress?:number;personal_notes?:string|null;completed?:boolean};Update:Partial<Database['public']['Tables']['user_library_items']['Insert']> };
  friendships: {Row:{id:string;requester_id:string;addressee_id:string;status:'pending'|'accepted'|'rejected'|'blocked';created_at:string;updated_at:string};Insert:{id?:string;requester_id:string;addressee_id:string;status?:'pending'|'accepted'|'rejected'|'blocked'};Update:{status?:'pending'|'accepted'|'rejected'|'blocked';updated_at?:string}};
}; Views: Record<string,never>; Functions: { atlas_save_trip: { Args: { trip_id: string|null; payload: Json }; Returns: string }; atlas_reorder_trip_stops: { Args: { target_trip_id: string; ordered_stop_ids: string[] }; Returns: undefined } }; Enums: { atlas_visibility: 'private'|'friends'|'public' } } }
