import Link from 'next/link';
import { ArrowUpRight, Map, MapPin, Route, Users } from 'lucide-react';
import type { ProfileSnapshot } from '@/types/profile';

export function ProfileAtlasBridge({ data }: { data: ProfileSnapshot }) {
  const located = data.memories.filter((memory) => memory.latitude !== undefined && memory.longitude !== undefined);
  const shared = data.memories.filter((memory) => memory.participantIds.length > 0);
  const name = data.access === 'owner' ? 'tu Atlas' : `el Atlas de ${data.profile.fullName || data.profile.username}`;
  return <section aria-labelledby="profile-atlas-title" className="overflow-hidden rounded-[2rem] border border-white/[.08] bg-[linear-gradient(145deg,rgba(15,23,42,.82),rgba(9,9,11,.96))] shadow-[0_24px_70px_rgba(0,0,0,.28),inset_0_1px_0_rgba(255,255,255,.05)]">
    <div className="grid gap-0 lg:grid-cols-[1.05fr_.95fr]">
      <div className="p-5 sm:p-6"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.18em] text-sky-300"><Map className="h-3.5 w-3.5" />Perfil conectado</div><h2 id="profile-atlas-title" className="mt-2 text-2xl font-semibold tracking-[-.035em] text-white">La cartografía de esta persona.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-500">El perfil resume quién es; el mapa muestra dónde ocurrieron sus memorias y con quién se cruzaron.</p><div className="mt-5 grid grid-cols-3 gap-2"><Metric value={located.length} label="en el mapa" icon={<MapPin />} /><Metric value={data.statistics.trips} label="viajes" icon={<Route />} /><Metric value={shared.length} label="compartidas" icon={<Users />} /></div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/home?person=${data.profile.id}`} className="inline-flex h-11 items-center gap-2 rounded-full bg-white px-4 text-sm font-semibold text-zinc-950 transition hover:bg-zinc-200">Explorar {name}<ArrowUpRight className="h-4 w-4" /></Link>{data.access === 'owner' && <Link href="/memories" className="inline-flex h-11 items-center rounded-full border border-white/10 px-4 text-sm font-medium text-zinc-300 transition hover:bg-white/[.06]">Abrir archivo</Link>}</div></div>
      <div className="border-t border-white/[.07] bg-black/15 p-5 lg:border-l lg:border-t-0 sm:p-6"><h3 className="text-[11px] font-semibold uppercase tracking-[.18em] text-zinc-500">Memorias que sostienen el mapa</h3>{data.memories.length ? <div className="mt-3 space-y-2">{data.memories.slice(0, 3).map((memory) => <div key={memory.id} className="group flex items-center gap-3 rounded-[1.15rem] border border-white/[.07] bg-white/[.025] p-3 transition hover:bg-white/[.05]"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-rose-400/10 text-rose-300"><MapPin className="h-4 w-4" /></span><Link href={`/memories/${memory.id}`} className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-white">{memory.title}</span><span className="mt-0.5 block truncate text-[11px] text-zinc-600">{memory.place || 'Sin lugar visible'}{memory.participantNames.length ? ` · con ${memory.participantNames.join(', ')}` : ''}</span></Link>{memory.latitude !== undefined && memory.longitude !== undefined && <Link href={`/home?memory=${memory.id}`} aria-label={`Ver ${memory.title} en el mapa`} className="rounded-full p-2 text-zinc-600 transition hover:bg-white/10 hover:text-sky-200"><Map className="h-4 w-4" /></Link>}</div>)}</div> : <p className="mt-4 text-sm leading-6 text-zinc-600">Todavía no hay memorias visibles para construir esta cartografía.</p>}<p className="mt-4 text-[11px] leading-5 text-zinc-700">La privacidad de cada memoria sigue siendo independiente del perfil.</p></div>
    </div>
  </section>;
}

function Metric({ value, label, icon }: { value: number; label: string; icon: React.ReactElement }) { return <div className="rounded-[1.1rem] border border-white/[.07] bg-white/[.035] p-3"><span className="text-zinc-600 [&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span><strong className="mt-2 block text-xl text-white">{value}</strong><span className="text-[10px] text-zinc-600">{label}</span></div>; }
