import Image from 'next/image';
import { CalendarDays, Edit3, Lock, LogOut, MapPin, ShieldCheck, Users } from 'lucide-react';
import type { AtlasProfile, ProfileAccess } from '@/types/profile';

export function ProfileHeader({ profile, access, onEdit, onSignOut }: { profile: AtlasProfile; access: ProfileAccess; onEdit?: () => void; onSignOut?: () => void }) {
  const privacy = profile.privacy === 'private' ? ['Privado', Lock] : profile.privacy === 'friends' ? ['Amigos', Users] : ['Público', ShieldCheck]; const PrivacyIcon = privacy[1] as typeof Lock;
  return <header className="overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_80%_0%,rgba(244,63,94,.18),transparent_38%),linear-gradient(145deg,#27272a,#09090b)] p-6 shadow-2xl sm:p-9"><div className="flex flex-col gap-6 sm:flex-row sm:items-start"><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-3xl border border-white/15 bg-zinc-800 text-center text-2xl font-semibold leading-[6rem] text-white">{profile.avatarUrl ? <Image src={profile.avatarUrl} alt={`Avatar de ${profile.fullName || profile.username}`} fill unoptimized={profile.avatarUrl.startsWith('http')} className="object-cover" /> : (profile.fullName || profile.username).slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-rose-300">@{profile.username}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-white">{profile.fullName || profile.username}</h1></div><div className="flex gap-2">{access === 'owner' && <button onClick={onEdit} className="rounded-full border border-white/10 p-2.5 text-zinc-300 hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400" aria-label="Editar perfil"><Edit3 className="h-4 w-4" /></button>}{access === 'owner' && <button onClick={onSignOut} className="rounded-full border border-white/10 p-2.5 text-zinc-300 hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400" aria-label="Cerrar sesión"><LogOut className="h-4 w-4" /></button>}</div></div>{profile.biography && <p className="mt-4 max-w-2xl leading-7 text-zinc-300">{profile.biography}</p>}<div className="mt-5 flex flex-wrap gap-3 text-xs text-zinc-400">{(profile.city || profile.country) && <span className="inline-flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5" />{[profile.city, profile.country].filter(Boolean).join(', ')}</span>}{profile.memberSince && <span className="inline-flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5" />Miembro desde {formatDate(profile.memberSince)}</span>}<span className="inline-flex items-center gap-1.5"><PrivacyIcon className="h-3.5 w-3.5" />{privacy[0] as string}</span></div></div></div></header>;
}
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('es', { month: 'long', year: 'numeric' }).format(date); }
