'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, Eye, EyeOff, Globe2, Loader2, Lock, Mail, Map, ShieldCheck, Sparkles, Wine } from 'lucide-react';
import { supabase } from '@/lib/supabase';

export default function LandingPage() {
  const router = useRouter(); const [isLogin,setIsLogin]=useState(true); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [showPassword,setShowPassword]=useState(false); const [message,setMessage]=useState(''); const [success,setSuccess]=useState(false); const [loading,setLoading]=useState(false);
  function switchMode(login:boolean){setIsLogin(login);setMessage('');setSuccess(false)}
  async function handleAuth(event:FormEvent){event.preventDefault();if(!email||!password){setMessage('Completa el correo y la contraseña.');return}setLoading(true);setMessage('');setSuccess(false);try{if(isLogin){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;router.push('/home')}else{const{error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/home`}});if(error)throw error;setSuccess(true);setMessage('Cuenta creada. Revisa tu correo para confirmarla.')}}catch(cause){setMessage(cause instanceof Error?cause.message:'No se pudo completar el acceso.')}finally{setLoading(false)}}
  async function signInGoogle(){setMessage('');setSuccess(false);const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/home`}});if(error)setMessage(error.message)}
  return <main className="relative min-h-screen overflow-hidden bg-[#050506] text-zinc-100 selection:bg-rose-300/30"><div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_18%_15%,rgba(190,24,93,.16),transparent_30%),radial-gradient(circle_at_82%_80%,rgba(14,116,144,.12),transparent_30%)]"/>
    <nav className="relative z-10 mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-sm font-bold text-black">A</span><span className="text-sm font-semibold tracking-[.18em] text-white">ATLAS</span></div><p className="hidden text-xs text-zinc-600 sm:block">Tu vida, sin ruido social.</p></nav>
    <div className="relative z-10 mx-auto grid max-w-7xl items-center gap-14 px-5 pb-16 pt-8 sm:px-8 lg:min-h-[calc(100vh-5rem)] lg:grid-cols-[1.15fr_.85fr] lg:py-14">
      <section><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-xs text-zinc-400"><Sparkles className="h-3.5 w-3.5 text-rose-300"/>Un archivo personal para toda una vida</div><h1 className="mt-7 max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.065em] text-white sm:text-7xl lg:text-[5.5rem]">Recuerda el mundo <span className="bg-gradient-to-r from-rose-200 via-orange-100 to-sky-200 bg-clip-text text-transparent">a tu manera.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-zinc-400 sm:text-lg">Memorias, vinos y rutas reales reunidos en un mapa privado. Sin seguidores, métricas ni una vida diseñada para los demás.</p>
        <div className="mt-10 grid max-w-2xl gap-3 sm:grid-cols-3"><Feature icon={<Map/>} title="Tu mapa" text="Momentos y rutas en contexto."/><Feature icon={<Wine/>} title="Tu bodega" text="Botellas ligadas a historias."/><Feature icon={<ShieldCheck/>} title="Tu privacidad" text="Tú decides quién puede verlo."/></div>
        <div className="mt-10 flex items-center gap-3 text-xs text-zinc-600"><Globe2 className="h-4 w-4"/><span>Diseñado para explorar. Construido para conservar.</span></div>
      </section>
      <section aria-labelledby="access-title" className="mx-auto w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[.055] p-5 shadow-[0_40px_120px_rgba(0,0,0,.55)] backdrop-blur-2xl sm:p-7"><div><p className="text-xs font-medium uppercase tracking-[.2em] text-zinc-500">Atlas personal</p><h2 id="access-title" className="mt-2 text-2xl font-semibold tracking-tight text-white">{isLogin?'Bienvenido de nuevo':'Crea tu espacio'}</h2><p className="mt-1 text-sm text-zinc-500">{isLogin?'Continúa donde lo dejaste.':'Empieza tu archivo privado.'}</p></div>
        <div className="mt-6 grid grid-cols-2 rounded-xl bg-black/30 p-1" role="tablist" aria-label="Acceso"><Tab active={isLogin} onClick={()=>switchMode(true)}>Entrar</Tab><Tab active={!isLogin} onClick={()=>switchMode(false)}>Crear cuenta</Tab></div>
        <form onSubmit={handleAuth} className="mt-6 space-y-4"><AuthField label="Correo" icon={<Mail/>}><input type="email" autoComplete="email" required value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="tu@correo.com" className="h-12 w-full bg-transparent pl-10 pr-4 text-sm text-white outline-none placeholder:text-zinc-600"/></AuthField><AuthField label="Contraseña" icon={<Lock/>}><input type={showPassword?'text':'password'} autoComplete={isLogin?'current-password':'new-password'} minLength={6} required value={password} onChange={(event)=>setPassword(event.target.value)} placeholder="Mínimo 6 caracteres" className="h-12 w-full bg-transparent pl-10 pr-12 text-sm text-white outline-none placeholder:text-zinc-600"/><button type="button" onClick={()=>setShowPassword((value)=>!value)} aria-label={showPassword?'Ocultar contraseña':'Mostrar contraseña'} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-zinc-600 hover:text-white">{showPassword?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></AuthField>{message&&<p role="status" className={`rounded-xl border px-3 py-2.5 text-xs ${success?'border-emerald-500/20 bg-emerald-500/10 text-emerald-200':'border-red-500/20 bg-red-500/10 text-red-200'}`}>{message}</p>}<button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-semibold text-black transition hover:bg-zinc-200 disabled:opacity-60">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<>{isLogin?'Entrar en Atlas':'Crear mi Atlas'}<ArrowRight className="h-4 w-4"/></>}</button></form>
        <div className="my-5 flex items-center gap-3 text-[10px] uppercase tracking-wider text-zinc-700"><span className="h-px flex-1 bg-white/10"/>o continúa con<span className="h-px flex-1 bg-white/10"/></div><button type="button" onClick={()=>void signInGoogle()} className="flex h-12 w-full items-center justify-center gap-3 rounded-xl border border-white/10 bg-black/20 text-sm font-medium text-zinc-300 transition hover:bg-white/[.06] hover:text-white"><GoogleIcon/>Google</button><p className="mt-5 text-center text-[11px] leading-5 text-zinc-600">Tus contenidos respetan la visibilidad que elijas: privada, círculo o pública.</p>
      </section>
    </div>
  </main>;
}
function Feature({icon,title,text}:{icon:React.ReactElement;title:string;text:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><span className="text-zinc-300 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><h3 className="mt-4 text-sm font-medium text-white">{title}</h3><p className="mt-1 text-xs leading-5 text-zinc-600">{text}</p></div>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" role="tab" aria-selected={active} onClick={onClick} className={`h-9 rounded-lg text-xs font-medium transition ${active?'bg-white/10 text-white shadow-sm':'text-zinc-600 hover:text-zinc-300'}`}>{children}</button>}
function AuthField({label,icon,children}:{label:string;icon:React.ReactElement;children:React.ReactNode}){return <label className="block text-xs font-medium text-zinc-400">{label}<span className="relative mt-2 block rounded-xl border border-white/10 bg-black/25 focus-within:border-white/25 focus-within:ring-4 focus-within:ring-white/5"><span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-zinc-600 [&>svg]:h-4 [&>svg]:w-4">{icon}</span>{children}</span></label>}
function GoogleIcon(){return <svg className="h-4 w-4" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.9h5.4a4.6 4.6 0 0 1-2 3v2.6h3.3c1.9-1.8 2.9-4.4 2.9-7.5Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.3l-3.3-2.6c-.9.6-2.1 1-3.4 1a5.9 5.9 0 0 1-5.5-4.1H3v2.7A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.5 14a6 6 0 0 1 0-4V7.3H3a10 10 0 0 0 0 9.4L6.5 14Z"/><path fill="#EA4335" d="M12 5.9c1.5 0 2.8.5 3.9 1.5l2.9-2.9A9.8 9.8 0 0 0 3 7.3L6.5 10A5.9 5.9 0 0 1 12 5.9Z"/></svg>}
