'use client';
import Image from 'next/image';
import { Check, Loader2, Users } from 'lucide-react';
import type { NetworkUser } from '@/lib/network';

export function ParticipantPicker({ users, selected, onChange, loading, error }: { users: NetworkUser[]; selected: string[]; onChange: (ids: string[]) => void; loading: boolean; error: string | null }) {
  const toggle = (id: string) => onChange(selected.includes(id) ? selected.filter((value) => value !== id) : [...selected, id]);
  return <fieldset><legend className="flex items-center gap-2 text-sm font-medium text-zinc-300"><Users className="h-4 w-4" />Compartir con amigos</legend><p className="mt-1 text-xs leading-5 text-zinc-600">Solo las personas que selecciones podrán ver este recuerdo. Ser amigos no comparte automáticamente nada.</p>{loading ? <div role="status" className="mt-3 flex items-center gap-2 text-xs text-zinc-500"><Loader2 className="h-3.5 w-3.5 animate-spin" />Cargando amigos…</div> : error ? <p role="alert" className="mt-3 text-xs text-red-300">{error}</p> : users.length === 0 ? <p className="mt-3 rounded-2xl border border-dashed border-white/10 p-4 text-center text-xs leading-5 text-zinc-600">Todavía no tienes amigos en Atlas. Añádelos desde tu perfil para poder compartir recuerdos con ellos.</p> : <div className="mt-3 flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{users.map((user) => { const active = selected.includes(user.id), name = user.fullName || user.username; return <button key={user.id} type="button" onClick={() => toggle(user.id)} aria-pressed={active} className={`relative flex min-w-[108px] flex-col items-center rounded-2xl border p-3 text-center transition active:scale-[.98] ${active ? 'border-rose-300/35 bg-rose-500/10 text-white shadow-[0_0_24px_rgba(244,63,94,.08)]' : 'border-white/10 bg-white/[.025] text-zinc-500 hover:bg-white/5'}`}><span className={`relative flex h-10 w-10 items-center justify-center overflow-hidden rounded-full bg-zinc-800 text-xs font-semibold text-white ${active ? 'ring-2 ring-rose-300/70' : 'ring-1 ring-white/10'}`}>{user.avatarUrl ? <Image src={user.avatarUrl} alt="" fill unoptimized={user.avatarUrl.startsWith('http')} className="object-cover" /> : name.slice(0, 2).toUpperCase()}</span><span className="mt-2 max-w-full truncate text-xs">{name}</span>{active && <span className="absolute right-2 top-2 rounded-full bg-rose-300 p-0.5 text-zinc-950"><Check className="h-3 w-3" /></span>}</button>; })}</div>}</fieldset>;
}
