'use client';
import { useEffect, useId, useState } from 'react';
import { Check, Loader2, MapPin, Search } from 'lucide-react';
import { searchPlaces, type AtlasPlace } from '@/lib/places/repository';

export function PlaceAutocomplete({ label, value, onChange, onSelect, required = false, placeholder = 'Ciudad, calle o lugar' }: { label: string; value: string; onChange: (value:string)=>void; onSelect:(place:AtlasPlace)=>void; required?:boolean; placeholder?:string }) {
  const id=useId(); const [places,setPlaces]=useState<AtlasPlace[]>([]); const [loading,setLoading]=useState(false); const [open,setOpen]=useState(false); const [selected,setSelected]=useState(false);
  useEffect(()=>{if(value.trim().length<3||selected){setPlaces([]);return}const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);try{setPlaces(await searchPlaces(value,controller.signal));setOpen(true)}catch(error){if((error as Error).name!=='AbortError')setPlaces([])}finally{setLoading(false)}},350);return()=>{clearTimeout(timer);controller.abort()}},[selected,value]);
  return <label htmlFor={id} className="relative block text-sm font-medium text-zinc-300">{label}<span className="relative mt-2 block"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-600"/><input id={id} required={required} value={value} onChange={(event)=>{onChange(event.target.value);setSelected(false)}} onFocus={()=>places.length&&setOpen(true)} autoComplete="off" placeholder={placeholder} className="h-12 w-full rounded-2xl border border-white/10 bg-white/[.045] pl-11 pr-10 text-sm text-white outline-none placeholder:text-zinc-600 focus:border-white/30 focus:ring-4 focus:ring-white/5"/>{loading?<Loader2 className="absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 animate-spin text-zinc-500"/>:selected?<Check className="absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-emerald-400"/>:null}</span>{open&&places.length>0&&<ul role="listbox" className="absolute z-50 mt-2 max-h-64 w-full overflow-y-auto rounded-2xl border border-white/10 bg-zinc-900 p-1.5 shadow-2xl">{places.map((place)=><li key={place.id}><button type="button" onClick={()=>{onChange(place.label);onSelect(place);setSelected(true);setOpen(false)}} className="flex w-full items-start gap-2 rounded-xl p-3 text-left text-xs text-zinc-300 hover:bg-white/5"><MapPin className="mt-0.5 h-3.5 w-3.5 shrink-0 text-rose-300"/><span>{place.label}</span></button></li>)}</ul>}</label>;
}
