'use client';

import { useState } from 'react';
import { Camera, Grid2X2, Heart, List, MapPin, Plus, Search, ShoppingBag, SlidersHorizontal, Star, TrendingUp, Users, Wine } from 'lucide-react';
import CaniaAssistant from '@/components/CaniaAssistant';
import { initialWineFilters, useWineLibrary } from '@/hooks/use-wine-library';
import type { WineItem, WineSort } from '@/types/wine';
import { WineBottleImage, WineCard, WineCreateDialog, WineDetailDialog, WineErrorState, WineFilters, WineGrid, WineListItem, WineLoadingState, WineNoResults } from '@/components/wine-ui';

export function WineLibrary() {
  const library = useWineLibrary();
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const activeFilters = Object.entries(library.filters).filter(([key, value]) => key === 'source' ? value !== 'all' : value !== '' && value !== false && value !== null).length;
  const isFiltered = Boolean(library.search || activeFilters);
  const reset = () => { library.setSearch(''); library.setFilters(initialWineFilters); };
  const featured = library.wines.find((wine) => wine.image_url || wine.photos.length) ?? library.wines[0];
  const countries = new Set(library.wines.map((wine) => wine.country).filter(Boolean)).size;
  const denominations = new Set(library.wines.map((wine) => wine.denomination).filter(Boolean)).size;
  const photographed = library.wines.filter((wine) => wine.image_url || wine.photos.length).length;

  return <main className="min-h-screen bg-zinc-950 pb-28 text-zinc-100 selection:bg-rose-500/30">
    <div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 sm:py-8 lg:px-8">
      <header className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_84%_12%,rgba(244,63,94,.2),transparent_30%),radial-gradient(circle_at_10%_100%,rgba(245,158,11,.08),transparent_32%),linear-gradient(135deg,rgba(39,39,42,.94),rgba(9,9,11,.98))] p-5 shadow-2xl shadow-black/20 sm:p-8">
        <div className="grid items-stretch gap-6 lg:grid-cols-[1fr_280px]"><div className="flex flex-col justify-between"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-rose-300"><Wine className="h-4 w-4" aria-hidden="true" />Bodega personal</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-[-.045em] text-white sm:text-5xl">Vinos con lugar, imagen y memoria.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400 sm:text-base">Una colección visual para reconocer la botella, recordar dónde la probaste y volver a su denominación en el mapa.</p></div><div className="mt-6 flex flex-wrap gap-2"><button onClick={() => setCreateOpen(true)} className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-white px-5 text-sm font-semibold text-zinc-950 shadow-lg transition hover:bg-rose-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400"><Plus className="h-4 w-4" aria-hidden="true" />Añadir vino</button>{featured&&<button onClick={()=>library.setSelectedWine(featured)} className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-white/10 bg-white/[.05] px-5 text-sm font-medium text-white transition hover:bg-white/[.09]"><Star className="h-4 w-4 text-amber-300"/>Abrir destacado</button>}</div></div>{featured&&<button type="button" onClick={()=>library.setSelectedWine(featured)} className="group relative hidden min-h-[270px] overflow-hidden rounded-[1.65rem] border border-white/10 bg-black/20 text-left lg:block"><WineBottleImage src={featured.image_url||featured.photos[0]} alt={featured.name} className="h-full min-h-[270px] rounded-none border-0" imageClassName="p-6 transition duration-500 group-hover:scale-[1.04]"/><span className="absolute inset-x-3 bottom-3 rounded-2xl border border-white/10 bg-black/65 p-3 backdrop-blur-xl"><span className="block text-[10px] font-semibold uppercase tracking-[.16em] text-rose-300">En foco</span><strong className="mt-1 block truncate text-sm text-white">{featured.name}</strong><span className="mt-0.5 block truncate text-[11px] text-zinc-400">{featured.denomination||featured.region}</span></span></button>}</div>
        <div className="mt-6 grid grid-cols-2 gap-2 border-t border-white/[.08] pt-5 sm:grid-cols-4"><HeroMetric icon={<Wine/>} value={library.wines.length} label="botellas"/><HeroMetric icon={<MapPin/>} value={countries} label="países"/><HeroMetric icon={<Star/>} value={denominations} label="denominaciones"/><HeroMetric icon={<Camera/>} value={photographed} label="con foto"/></div>
      </header>

      {!library.loading&&library.wines.length>0&&<MarketplaceHighlights wines={library.wines} userId={library.userId} onOpen={library.setSelectedWine}/>}

      <section aria-label="Controles de la bodega" className="sticky top-0 z-20 -mx-4 mt-5 border-y border-white/10 bg-zinc-950/90 px-4 py-3 backdrop-blur-xl sm:static sm:mx-0 sm:mt-7 sm:rounded-2xl sm:border sm:bg-zinc-900/60">
        <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
          <label className="relative flex-1"><span className="sr-only">Buscar vinos</span><Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500" aria-hidden="true" /><input type="search" value={library.search} onChange={(event) => library.setSearch(event.target.value)} placeholder="Nombre, bodega, uva, región o país" className="h-12 w-full rounded-xl border border-white/10 bg-zinc-950 pl-11 pr-4 text-sm text-white outline-none placeholder:text-zinc-600 focus:border-rose-400 focus:ring-2 focus:ring-rose-400/20" /></label>
          <div className="flex gap-2 overflow-x-auto"><button onClick={() => setFiltersOpen(true)} className="relative inline-flex h-11 shrink-0 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm text-zinc-300 hover:bg-white/5 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400"><SlidersHorizontal className="h-4 w-4" />Filtros{activeFilters > 0 && <span className="rounded-full bg-rose-500 px-1.5 text-[11px] text-white">{activeFilters}</span>}</button><label className="sr-only" htmlFor="wine-sort">Ordenar vinos</label><select id="wine-sort" value={library.sort} onChange={(event) => library.setSort(event.target.value as WineSort)} className="h-11 shrink-0 rounded-xl border border-white/10 bg-zinc-950 px-3 text-sm text-zinc-300 outline-none focus:border-rose-400"><option value="recent">Más recientes</option><option value="rating">Mejor valorados</option><option value="price-asc">Menor precio</option><option value="price-desc">Mayor precio</option><option value="vintage">Añada</option><option value="alphabetical">Orden alfabético</option></select><div className="flex rounded-xl border border-white/10 p-1" aria-label="Tipo de vista"><ViewButton active={library.view === 'grid'} onClick={() => library.setView('grid')} label="Vista de cuadrícula"><Grid2X2 className="h-4 w-4" /></ViewButton><ViewButton active={library.view === 'list'} onClick={() => library.setView('list')} label="Vista de lista"><List className="h-4 w-4" /></ViewButton></div></div>
        </div>
      </section>

      <div className="mt-6 flex items-center justify-between"><p className="text-sm text-zinc-400" role="status" aria-live="polite">{library.loading ? 'Cargando…' : `${library.filteredWines.length} ${library.filteredWines.length === 1 ? 'vino' : 'vinos'}`}</p>{isFiltered && <button onClick={reset} className="text-xs text-rose-300 hover:text-rose-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400">Limpiar búsqueda y filtros</button>}</div>
      {library.error && library.wines.length > 0 && <div role="alert" className="mt-4 flex items-center justify-between gap-3 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3 text-sm text-red-200"><span>{library.error}</span><button onClick={library.clearError} className="shrink-0 rounded-lg px-2 py-1 hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-red-300">Cerrar</button></div>}
      <div className="mt-4"><WineResults library={library} isFiltered={isFiltered} reset={reset} /></div>
    </div>

    {filtersOpen && <div className="fixed inset-0 z-40 bg-black/70 backdrop-blur-sm" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setFiltersOpen(false)}><aside role="dialog" aria-modal="true" aria-label="Filtros de vinos" className="absolute inset-y-0 right-0 w-[min(92vw,390px)] overflow-y-auto border-l border-white/10 bg-zinc-950 p-6 shadow-2xl"><WineFilters filters={library.filters} options={library.options} onChange={library.setFilters} onClose={() => setFiltersOpen(false)} /></aside></div>}
    <WineDetailDialog wine={library.selectedWine} onClose={() => library.setSelectedWine(null)} onFavorite={(wine) => void library.toggleFavorite(wine)} />
    <WineCreateDialog open={createOpen} onClose={() => setCreateOpen(false)} onCreated={library.addWine} existingWines={library.wines} />
    <CaniaAssistant userWines={library.wines.map((wine) => ({ ...wine, winery: wine.winery || '', vintage: wine.vintage || 0, rating: wine.rating || 0, supermarket: wine.supermarket || '', price: wine.price || 0, tasting_notes: wine.tasting_notes || '', image_url: wine.image_url || '' }))} />
  </main>;
}

function WineResults({ library, isFiltered, reset }: { library: ReturnType<typeof useWineLibrary>; isFiltered: boolean; reset: () => void }) {
  if (library.loading) return <WineLoadingState />;
  if (library.error && library.wines.length === 0) return <WineErrorState message={library.error} onRetry={() => void library.refresh()} />;
  if (library.filteredWines.length === 0) return <WineNoResults filtered={isFiltered} onReset={reset} />;
  if (library.view === 'list') return <div className="space-y-3">{library.filteredWines.map((wine) => <WineListItem key={wine.id} wine={wine} onOpen={() => library.setSelectedWine(wine)} onFavorite={() => void library.toggleFavorite(wine)} />)}</div>;
  return <WineGrid>{library.filteredWines.map((wine) => <WineCard key={wine.id} {...cardProps(wine)} className="h-full" action={<div className="flex gap-2"><button onClick={() => void library.toggleFavorite(wine)} aria-pressed={wine.favorite} aria-label={`${wine.favorite ? 'Quitar' : 'Añadir'} ${wine.name} ${wine.favorite ? 'de' : 'a'} favoritos`} className="rounded-full border border-white/10 p-2.5 text-zinc-400 hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400"><Heart className={`h-4 w-4 ${wine.favorite ? 'fill-rose-500 text-rose-500' : ''}`} /></button><button onClick={() => library.setSelectedWine(wine)} className="flex-1 rounded-full bg-white px-4 py-2.5 text-sm font-semibold text-zinc-950 hover:bg-rose-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400">Ver detalle</button></div>} />)}</WineGrid>;
}

function ViewButton({ active, onClick, label, children }: { active: boolean; onClick: () => void; label: string; children: React.ReactNode }) { return <button onClick={onClick} aria-label={label} aria-pressed={active} className={`rounded-lg p-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 ${active ? 'bg-white text-zinc-950' : 'text-zinc-500 hover:text-white'}`}>{children}</button>; }
function cardProps(wine: WineItem) { return { name: wine.name, winery: wine.winery, imageUrl: wine.image_url, photos: wine.photos, user: wine.owner_name, vintage: wine.vintage, country: wine.country, region: wine.denomination || wine.region, grapes: wine.grapes, supermarket: wine.supermarket, shop: wine.shop, rating: wine.rating, price: wine.price, notes: wine.notes || wine.tasting_notes, favorite: wine.favorite, visibility: wine.visibility, participants: wine.participants, linkedMemories: wine.linked_memories, createdAt: formatDate(wine.created_at) }; }
function formatDate(value?: string) { if (!value) return undefined; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('es', { dateStyle: 'medium' }).format(date); }
function HeroMetric({icon,value,label}:{icon:React.ReactElement;value:number;label:string}){return <div className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.035] px-3 py-3"><span className="text-rose-300 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><span><strong className="block text-lg leading-none text-white">{value}</strong><span className="mt-1 block text-[9px] uppercase tracking-[.13em] text-zinc-600">{label}</span></span></div>}

function MarketplaceHighlights({ wines, userId, onOpen }: { wines: WineItem[]; userId: string | null; onOpen: (wine: WineItem) => void }) {
  const popularSpain = [...wines].filter((wine)=>wine.is_popular&&normalizeCountry(wine.country)==='espana').sort((a,b)=>(b.rating??0)-(a.rating??0)||(b.price??0)-(a.price??0)).slice(0,5);
  const userWines = wines.filter((wine)=>Boolean(wine.user_id));
  const mine = wines.filter((wine)=>Boolean(userId&&wine.user_id===userId));
  const marketMap = new Map<string,{name:string;count:number;prices:number[]}>();
  wines.filter((wine)=>wine.is_popular).forEach((wine)=>{const name=wine.supermarket||wine.shop;if(!name)return;const current=marketMap.get(name)??{name,count:0,prices:[]};current.count+=1;if(wine.price!==undefined)current.prices.push(wine.price);marketMap.set(name,current)});
  const markets=[...marketMap.values()].sort((a,b)=>b.count-a.count).slice(0,4);
  return <section className="mt-5 grid gap-3 lg:grid-cols-[1fr_310px]" aria-label="Mercado y vinos de la comunidad">
    <div className="overflow-hidden rounded-[1.7rem] border border-white/[.08] bg-[linear-gradient(145deg,rgba(39,39,42,.58),rgba(9,9,11,.92))] p-4 sm:p-5"><div className="flex items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.18em] text-amber-300"><TrendingUp className="h-3.5 w-3.5"/>Más vendidos en España</p><h2 className="mt-1.5 text-lg font-semibold tracking-[-.025em]">El pulso real del mercado</h2></div><span className="text-[9px] text-zinc-600">Datos de Supabase</span></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{popularSpain.map((wine,index)=><button key={wine.id} type="button" onClick={()=>onOpen(wine)} className="group flex min-w-[190px] items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-2.5 text-left transition hover:-translate-y-0.5 hover:bg-white/[.055]"><WineBottleImage src={wine.image_url||wine.photos[0]} alt="" className="h-20 w-14 shrink-0 rounded-xl border-white/[.07]" imageClassName="p-2"/><span className="min-w-0"><span className="text-[8px] font-semibold uppercase tracking-[.12em] text-amber-300/70">Top {index+1}</span><strong className="mt-1 block truncate text-xs text-white">{wine.name}</strong><span className="mt-1 block truncate text-[9px] text-zinc-500">{wine.supermarket||wine.shop} · {wine.price!==undefined?`${wine.price.toFixed(2)} €`:'Precio variable'}</span><span className="mt-1 block truncate text-[9px] text-zinc-600">{wine.denomination||wine.region}</span></span></button>)}</div></div>
    <aside className="rounded-[1.7rem] border border-white/[.08] bg-white/[.025] p-4 sm:p-5"><div className="flex items-center justify-between"><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.18em] text-rose-300"><ShoppingBag className="h-3.5 w-3.5"/>Top mercados</p><span className="text-[9px] text-zinc-600">{wines.filter((wine)=>wine.is_popular).length} referencias</span></div><div className="mt-3 grid grid-cols-2 gap-2">{markets.map((market)=><div key={market.name} className="rounded-xl border border-white/[.06] bg-black/10 p-3"><strong className="block truncate text-[11px] text-white">{market.name}</strong><span className="mt-1 block text-[9px] text-zinc-600">{market.count} vinos · {market.prices.length?(market.prices.reduce((sum,value)=>sum+value,0)/market.prices.length).toFixed(2):'—'} € med.</span></div>)}</div><div className="mt-4 flex items-center gap-3 border-t border-white/[.07] pt-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-300/[.07] text-sky-200"><Users className="h-4 w-4"/></span><div><strong className="block text-[11px] text-white">{mine.length} en tu bodega · {userWines.length} de usuarios</strong><span className="mt-0.5 block text-[9px] text-zinc-600">El catálogo y las colecciones personales conviven sin mezclarse.</span></div></div></aside>
  </section>;
}

function normalizeCountry(value?:string){return (value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
