import { supabase } from '@/lib/supabase';

export type NetworkRelationship='friend'|'pending'|'public';
export interface NetworkUser{id:string;username:string;fullName:string;avatarUrl?:string;relationship:NetworkRelationship;requestId?:string;requestDirection?:'incoming'|'outgoing'}
type FriendshipRow={id:string;requester_id:string;addressee_id:string;status:string};

export async function fetchUserNetwork(currentUserId:string):Promise<NetworkUser[]>{const[profilesResult,friendshipsResult]=await Promise.all([supabase.from('profiles').select('id,username,full_name,avatar_url').neq('id',currentUserId),supabase.from('friendships').select('*').or(`requester_id.eq.${currentUserId},addressee_id.eq.${currentUserId}`)]);if(profilesResult.error)throw profilesResult.error;if(friendshipsResult.error)throw friendshipsResult.error;const states=new Map<string,Pick<NetworkUser,'relationship'|'requestId'|'requestDirection'>>();const blocked=new Set<string>();(friendshipsResult.data as FriendshipRow[]??[]).forEach((row)=>{const outgoing=row.requester_id===currentUserId,other=outgoing?row.addressee_id:row.requester_id;if(row.status==='blocked'){blocked.add(other);return;}if(row.status==='accepted')states.set(other,{relationship:'friend',requestId:row.id});else if(row.status==='pending')states.set(other,{relationship:'pending',requestId:row.id,requestDirection:outgoing?'outgoing':'incoming'});});return(profilesResult.data??[]).flatMap((profile)=>blocked.has(profile.id)?[]:[{id:profile.id,username:profile.username||'',fullName:profile.full_name||profile.username||'Usuario Atlas',avatarUrl:profile.avatar_url||undefined,relationship:states.get(profile.id)?.relationship??'public',requestId:states.get(profile.id)?.requestId,requestDirection:states.get(profile.id)?.requestDirection}]);}

export async function updateUserRelationship(currentUserId:string,targetUserId:string,relationship:NetworkRelationship):Promise<void>{if(relationship==='friend'){const{error}=await supabase.from('friendships').insert({requester_id:currentUserId,addressee_id:targetUserId,status:'pending'});if(error)throw error;return;}const{error}=await supabase.from('friendships').delete().or(`and(requester_id.eq.${currentUserId},addressee_id.eq.${targetUserId}),and(requester_id.eq.${targetUserId},addressee_id.eq.${currentUserId})`);if(error)throw error;}
export async function resolveFriendRequest(requestId:string,accept:boolean){const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Debes iniciar sesión.');if(accept){const{error}=await supabase.from('friendships').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',requestId).eq('addressee_id',auth.user.id);if(error)throw error;}else{const{error}=await supabase.from('friendships').delete().eq('id',requestId);if(error)throw error;}}
export async function listShareableUsers():Promise<NetworkUser[]>{const{data,error}=await supabase.auth.getUser();if(error||!data.user)throw new Error('Debes iniciar sesión para seleccionar participantes.');return(await fetchUserNetwork(data.user.id)).filter((user)=>user.relationship==='friend');}
