'use client';
import { useEffect } from 'react';
import L from 'leaflet';
import MarkerClusterGroup from 'react-leaflet-cluster';
import { MapContainer, Marker, Polyline, Popup, TileLayer, useMap, ZoomControl } from 'react-leaflet';
import type { AtlasMapPoint, MapLayer } from '@/types/map';
import { WineCard } from '@/components/wine-ui';
import { MapOwner } from './MapOwner';
import { MemoryPopup } from './MemoryPopup';
import { TripPopup } from './TripPopup';

export function AtlasLeafletMap({ points }: { points: AtlasMapPoint[] }) { const trips = points.filter((point) => point.trip && point.trip.points.length > 1); return <MapContainer center={[20, 0]} zoom={3} minZoom={2} scrollWheelZoom className="h-full w-full bg-zinc-950" zoomControl={false}><ZoomControl position="bottomright" /><TileLayer attribution='&copy; OpenStreetMap &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png" /><FitBounds points={points} /><MarkerClusterGroup chunkedLoading chunkInterval={100} chunkDelay={20} removeOutsideVisibleBounds spiderfyOnMaxZoom>{points.map((point) => <Marker key={point.id} position={[point.latitude, point.longitude]} icon={icon(point.layer)} title={point.title} keyboard><Popup className="atlas-map-popup" maxWidth={340} minWidth={260}>{point.wine ? <div className="w-[300px] bg-zinc-950 p-2"><WineCard name={point.wine.name} winery={point.wine.winery} imageUrl={point.wine.image_url} vintage={point.wine.vintage} country={point.wine.country} region={point.wine.region} grapes={point.wine.grapes} rating={point.wine.rating} price={point.wine.price} favorite={point.wine.favorite} visibility={point.wine.visibility} /><div className="px-2 pb-2"><MapOwner id={point.ownerId} name={point.ownerName} avatarUrl={point.ownerAvatarUrl} /></div></div> : point.trip ? <TripPopup trip={point.trip} /> : point.memory ? <MemoryPopup memory={point.memory} /> : null}</Popup></Marker>)}</MarkerClusterGroup>{trips.map((point) => <Polyline key={`route-${point.id}`} positions={point.trip!.points.map((item) => [item.latitude,item.longitude])} pathOptions={{ color: '#38bdf8', weight: 3, opacity: .75 }} />)}</MapContainer>; }
function FitBounds({ points }: { points: AtlasMapPoint[] }) { const map = useMap(); useEffect(() => { if (!points.length) return; const bounds = L.latLngBounds(points.map((point) => [point.latitude,point.longitude])); map.fitBounds(bounds, { padding: [44,44], maxZoom: 12, animate: points.length < 300 }); }, [map,points]); return null; }
const cache = new Map<MapLayer,L.DivIcon>();
function icon(layer: MapLayer) { const existing = cache.get(layer); if (existing) return existing; const colors: Record<MapLayer,string> = { memories:'#f43f5e', wines:'#a855f7', trips:'#38bdf8', favorites:'#f59e0b', restaurants:'#10b981' }; const value = L.divIcon({ className: 'atlas-map-marker', html: `<span style="background:${colors[layer]}"></span>`, iconSize: [30,30], iconAnchor: [15,15], popupAnchor: [0,-14] }); cache.set(layer,value); return value; }
