'use client';

import { Search, SlidersHorizontal, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { AtlasMapFilters, AtlasMapSnapshot, MapLayer, MapSource } from '@/types/map';
import { MapLayerSelector } from './MapLayerSelector';

export function MapToolbar({ filters, snapshot, count, setQuery, setYear, setParticipant, toggleLayer, toggleSource }: { filters: AtlasMapFilters; snapshot: AtlasMapSnapshot; count: number; setQuery: (value: string) => void; setYear: (value: string) => void; setParticipant: (value: string) => void; toggleLayer: (value: MapLayer) => void; toggleSource: (value: MapSource) => void }) {
  const [open,setOpen]=useState(false),[focused,setFocused]=useState(false);
  const suggestions=useMemo(()=>{const query=filters.query.trim().toLocaleLowerCase('es');if(query.length<2)return [];return snapshot.points.filter((point)=>[point.title,point.subtitle,point.memory?.city,point.memory?.country,point.wine?.region,point.wine?.winery].filter(Boolean).join(' ').toLocaleLowerCase('es').includes(query)).slice(0,5);},[filters.query,snapshot.points]);
  return <div className="absolute inset-x-3 top-3 z-[900] sm:inset-x-5 sm:top-5"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-2"><div className="relative min-w-0 flex-1"><label className="relative block"><span className="sr-only">Buscar en Atlas</span><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500"/><input type="search" value={filters.query} onFocus={()=>setFocused(true)} onBlur={()=>setTimeout(()=>setFocused(false),120)} onChange={(event)=>setQuery(event.target.value)} placeholder="Ciudad, memoria, vino o denominación" className="h-12 w-full rounded-[1.15rem] border border-white/50 bg-white/90 pl-11 pr-11 text-sm text-zinc-900 shadow-[0_12px_40px_rgba(0,0,0,.25)] backdrop-blur-2xl outline-none placeholder:text-zinc-500 focus:bg-white focus:ring-4 focus:ring-white/30"/>{filters.query&&<button type="button" onClick={()=>setQuery('')} aria-label="Limpiar búsqueda" className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full bg-zinc-200 p-1 text-zinc-600"><X className="h-3.5 w-3.5"/></button>}</label>{focused&&suggestions.length>0&&<div className="absolute inset-x-0 top-14 overflow-hidden rounded-[1.15rem] border border-black/5 bg-white/95 p-1.5 text-zinc-900 shadow-2xl backdrop-blur-2xl">{suggestions.map((point)=><button key={point.id} type="button" onMouseDown={()=>setQuery(point.title)} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left hover:bg-zinc-100"><span className="min-w-0"><span className="block truncate text-sm font-medium">{point.title}</span><span className="block truncate text-xs text-zinc-500">{point.subtitle||point.layer}</span></span><span className="ml-3 text-[10px] uppercase tracking-wider text-zinc-400">{point.layer}</span></button>)}</div>}</div><button onClick={()=>setOpen(true)} aria-expanded={open} aria-label="Abrir capas y filtros" className="relative flex h-12 items-center gap-2 rounded-[1.15rem] border border-white/50 bg-white/90 px-4 text-sm font-medium text-zinc-900 shadow-xl backdrop-blur-2xl focus:outline-none focus-visible:ring-4 focus-visible:ring-white/30"><SlidersHorizontal className="h-4 w-4"/><span className="hidden sm:inline">Explorar</span><span className="rounded-full bg-zinc-900 px-1.5 py-0.5 text-[10px] text-white">{count}</span></button></div><p className="mt-2 pl-3 text-[11px] font-medium text-white drop-shadow">Busca dentro de tu archivo y del contenido autorizado</p></div>
  {open&&<div className="fixed inset-0 z-[1000] bg-black/40 backdrop-blur-sm" onMouseDown={(event)=>event.target===event.currentTarget&&setOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="map-filters-title" className="absolute inset-x-2 bottom-2 max-h-[85dvh] overflow-y-auto rounded-[2rem] border border-white/10 bg-zinc-950/95 p-5 shadow-2xl backdrop-blur-2xl sm:inset-y-3 sm:left-auto sm:right-3 sm:w-96"><div className="mb-5 flex items-center justify-between"><div><h2 id="map-filters-title" className="font-semibold text-white">Explorar Atlas</h2><p className="mt-1 text-xs text-zinc-500">Elige qué quieres ver en el mapa.</p></div><button onClick={()=>setOpen(false)} aria-label="Cerrar filtros" className="rounded-full bg-white/5 p-2 text-zinc-400 hover:bg-white/10"><X className="h-5 w-5"/></button></div><MapLayerSelector filters={filters} toggleLayer={toggleLayer} toggleSource={toggleSource}/><div className="mt-5 grid gap-4"><Select label="Año" value={filters.year} onChange={setYear} options={snapshot.years.map((value)=>({value,label:value}))}/><Select label="Participante" value={filters.participant} onChange={setParticipant} options={snapshot.participants.map((person)=>({value:person.id,label:person.name}))}/></div></section></div>}</div>;
}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<{value:string;label:string}>}){return <label className="text-xs text-zinc-500">{label}<select value={value} onChange={(event)=>onChange(event.target.value)} className="mt-1 h-12 w-full rounded-2xl border border-white/10 bg-zinc-900 px-3 text-sm text-white outline-none focus:border-white/30"><option value="">Todos</option>{options.map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>}
