import Link from 'next/link';
import { ArrowUpRight, Bookmark, CalendarDays, Eye, MapPin, Star, Store, Users } from 'lucide-react';
import type { ProfileMemory } from '@/types/profile';
import { MapOwner } from './MapOwner';

export function MemoryPopup({ memory }: { memory: ProfileMemory }) {
  const KindIcon=memory.isRestaurant?Store:MapPin;
  return <article className="w-64 space-y-3 bg-zinc-950 p-3 text-zinc-100"><div><span className={`flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider ${memory.isRestaurant?'text-emerald-300':'text-rose-300'}`}><KindIcon className="h-3 w-3"/>{memory.isRestaurant ? memory.restaurantStatus === 'wishlist' ? 'Quiero ir' : 'Guía privada' : memory.category || 'Memoria'}</span><h3 className="mt-1 text-base font-semibold text-white">{memory.title}</h3>{memory.isRestaurant&&<div className="mt-2 flex flex-wrap gap-1 text-[9px] text-emerald-100/70">{memory.restaurantCuisine&&<span className="rounded-full bg-emerald-300/[.08] px-2 py-1">{memory.restaurantCuisine}</span>}{memory.restaurantPriceLevel&&<span className="rounded-full bg-emerald-300/[.08] px-2 py-1">{'€'.repeat(memory.restaurantPriceLevel)}</span>}{memory.restaurantRating!==undefined&&<span className="flex items-center gap-1 rounded-full bg-amber-300/[.08] px-2 py-1 text-amber-100"><Star className="h-2.5 w-2.5 fill-current"/>{memory.restaurantRating}</span>}</div>}{memory.restaurantMustOrder&&<p className="mt-2 flex gap-1.5 rounded-lg bg-white/[.04] p-2 text-[10px] leading-4 text-zinc-400"><Bookmark className="mt-0.5 h-3 w-3 shrink-0 text-emerald-300"/>{memory.restaurantMustOrder}</p>}{memory.description && <p className="mt-2 line-clamp-3 text-xs leading-5 text-zinc-400">{memory.description}</p>}</div><div className="space-y-1.5 text-xs text-zinc-500">{memory.place && <p className="flex gap-1.5"><MapPin className="h-3.5 w-3.5" />{memory.place}</p>}{(memory.date || memory.createdAt) && <p className="flex gap-1.5"><CalendarDays className="h-3.5 w-3.5" />{formatDate(memory.date || memory.createdAt!)}</p>}<p className="flex gap-1.5"><Eye className="h-3.5 w-3.5" />{memory.visibility === 'private' ? 'Solo quien la creó' : 'Compartida con su círculo'}</p>{memory.participantNames.length > 0 && <p className="flex gap-1.5"><Users className="h-3.5 w-3.5" />{memory.participantNames.join(', ')}</p>}</div><MapOwner id={memory.userId} name={memory.ownerName} avatarUrl={memory.ownerAvatarUrl} /><Link href={`/memories/${memory.id}`} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-medium text-white transition hover:bg-white/10"><span>Abrir {memory.isRestaurant?'restaurante':'memoria'}</span><ArrowUpRight className="h-3.5 w-3.5" /></Link></article>;
}

function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('es', { dateStyle: 'medium' }).format(date); }
