'use client';

import Image from 'next/image';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Camera, Check, Heart, Loader2, Sparkles, X } from 'lucide-react';
import { createWine, deleteWinePhoto, uploadWinePhoto } from '@/lib/wines/repository';
import { cleanBottlePhoto } from '@/lib/images/clean-bottle-photo';
import type { WineItem } from '@/types/wine';

type Draft={name:string;winery:string;vintage:string;country:string;region:string;denomination:string;grapes:string;description:string;rating:string;favorite:boolean;shop:string;price:string;notes:string;dateTasted:string};
const initial:Draft={name:'',winery:'',vintage:'',country:'',region:'',denomination:'',grapes:'',description:'',rating:'',favorite:false,shop:'',price:'',notes:'',dateTasted:''};

export function WineCreateDialog({open,onClose,onCreated,existingWines=[]}:{open:boolean;onClose:()=>void;onCreated:(wine:WineItem)=>void;existingWines?:WineItem[]}){
  const closeRef=useRef<HTMLButtonElement>(null);const[step,setStep]=useState(1),[draft,setDraft]=useState(initial),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[processing,setProcessing]=useState(false),[saving,setSaving]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState<string|null>(null),[photoNotice,setPhotoNotice]=useState<string|null>(null);
  const suggestions=useMemo(()=>draft.name.trim().length<2?[]:existingWines.filter((wine)=>normalize(wine.name).includes(normalize(draft.name))).slice(0,4),[draft.name,existingWines]);
  useEffect(()=>{if(!open)return;closeRef.current?.focus();const escape=(event:KeyboardEvent)=>event.key==='Escape'&&!saving&&onClose();document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[onClose,open,saving]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  if(!open)return null;
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft((current)=>({...current,[key]:value}));
  function complete(wine:WineItem){setDraft((current)=>({...current,name:wine.name,winery:wine.winery??'',vintage:wine.vintage?String(wine.vintage):'',country:wine.country??'',region:wine.region??'',denomination:wine.denomination??'',grapes:wine.grapes.join(', '),description:wine.description??''}));}
  async function choosePhoto(next:File){setProcessing(true);setError(null);setPhotoNotice(null);try{const prepared=await cleanBottlePhoto(next);setFile(prepared);setPhotoNotice('Imagen optimizada para Atlas.');}catch{setFile(next);setPhotoNotice('Tu navegador no pudo optimizar este formato; conservaremos el archivo original.');}finally{if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(next));setProcessing(false);}}
  async function submit(event:FormEvent){event.preventDefault();if(!draft.name.trim()){setStep(2);setError('El nombre es el único dato obligatorio.');return;}setSaving(true);setError(null);setProgress(12);let imagePath:string|undefined;try{if(file){setProgress(30);imagePath=await uploadWinePhoto(file);}setProgress(68);const wine=await createWine({name:draft.name.trim(),winery:empty(draft.winery),vintage:number(draft.vintage),country:empty(draft.country),region:empty(draft.region),denomination:empty(draft.denomination),grapes:list(draft.grapes),description:empty(draft.description),image_path:imagePath,rating:number(draft.rating),favorite:draft.favorite,shop:empty(draft.shop),price:number(draft.price)??null,tasting_notes:empty(draft.notes),date_tasted:empty(draft.dateTasted)});setProgress(100);onCreated(wine);reset();onClose();}catch(cause){if(imagePath)await deleteWinePhoto(imagePath);setError(cause instanceof Error?cause.message:'No se pudo guardar el vino. Tus datos siguen en el formulario.');}finally{setSaving(false);}}
  function reset(){setStep(1);setDraft(initial);setFile(null);if(preview)URL.revokeObjectURL(preview);setPreview(null);setProgress(0);setPhotoNotice(null);}
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/75 backdrop-blur-sm sm:items-center sm:p-6"><section role="dialog" aria-modal="true" aria-labelledby="create-wine-title" className="max-h-[95dvh] w-full max-w-xl overflow-y-auto rounded-t-[2rem] border border-white/10 bg-zinc-950 p-5 shadow-2xl sm:rounded-[2rem] sm:p-7"><header className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-widest text-rose-300">Paso {step} de 3</p><h2 id="create-wine-title" className="mt-1 text-2xl font-semibold text-white">{step===1?'Fotografía':step===2?'Identifica el vino':'Tu experiencia'}</h2><p className="mt-1 text-xs text-zinc-500">{step===1?'Haz una foto o elige una imagen real de la botella.':step===2?'Corrige solo lo que conozcas; excepto el nombre, todo es opcional.':'Estos datos son personales y se guardan en tu cuenta.'}</p></div><button ref={closeRef} disabled={saving} onClick={onClose} aria-label="Cerrar" className="rounded-full p-2 text-zinc-400 hover:bg-white/10 disabled:opacity-50"><X className="h-5 w-5"/></button></header>
  <form onSubmit={submit} className="mt-6"><div className="mb-6 grid grid-cols-3 gap-2" aria-hidden="true">{[1,2,3].map((value)=><span key={value} className={`h-1 rounded-full ${value<=step?'bg-rose-400':'bg-white/10'}`}/>)}</div>
  {step===1&&<div><label className="grid cursor-pointer gap-4 rounded-3xl border border-dashed border-white/15 p-4 hover:bg-white/[.03]">{preview?<span className="relative h-72 overflow-hidden rounded-2xl bg-white/5"><Image src={preview} alt="Fotografía elegida" fill unoptimized className="object-contain p-3"/></span>:<span className="flex h-64 flex-col items-center justify-center rounded-2xl bg-white/[.03] text-zinc-500"><Camera className="h-8 w-8"/><strong className="mt-3 text-sm text-white">Tomar o elegir fotografía</strong><span className="mt-1 text-xs">JPEG, PNG, WebP, HEIC · máximo 12 MB</span></span>}<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" className="sr-only" onChange={(event)=>{const next=event.target.files?.[0];if(next)void choosePhoto(next);}}/></label>{processing&&<p className="mt-3 flex items-center gap-2 text-xs text-zinc-400"><Loader2 className="h-3.5 w-3.5 animate-spin"/>Preparando imagen…</p>}{photoNotice&&<p className="mt-3 text-xs text-emerald-300">{photoNotice}</p>}</div>}
  {step===2&&<div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Input label="Nombre del vino *" value={draft.name} onChange={(event)=>set('name',event.target.value)} autoFocus placeholder="Ej. Viña Ardanza"/>{suggestions.length>0&&<div className="mt-2 flex flex-wrap gap-2">{suggestions.map((wine)=><button key={wine.id} type="button" onClick={()=>complete(wine)} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-zinc-300"><Sparkles className="mr-1 inline h-3 w-3 text-rose-300"/>{wine.name}{wine.vintage?` · ${wine.vintage}`:''}</button>)}</div>}</div><Input label="Bodega" value={draft.winery} onChange={(event)=>set('winery',event.target.value)}/><Input label="Añada" type="number" min="1900" max="2100" value={draft.vintage} onChange={(event)=>set('vintage',event.target.value)}/><Input label="País" list="wine-countries" value={draft.country} onChange={(event)=>set('country',event.target.value)}/><Input label="Región" value={draft.region} onChange={(event)=>set('region',event.target.value)}/><Input label="Denominación" value={draft.denomination} onChange={(event)=>set('denomination',event.target.value)}/><Input label="Uvas" value={draft.grapes} onChange={(event)=>set('grapes',event.target.value)} placeholder="Tempranillo, Garnacha"/><label className="sm:col-span-2 text-sm text-zinc-300">Descripción general<textarea value={draft.description} onChange={(event)=>set('description',event.target.value)} rows={3} className="mt-1 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-white outline-none focus:border-rose-400"/></label><datalist id="wine-countries"><option value="España"/><option value="Francia"/><option value="Italia"/><option value="Portugal"/><option value="Argentina"/><option value="Chile"/><option value="Estados Unidos"/><option value="Australia"/></datalist></div>}
  {step===3&&<div className="grid gap-4 sm:grid-cols-2"><Input label="Valoración" type="number" min="0" max="5" step="0.5" value={draft.rating} onChange={(event)=>set('rating',event.target.value)} placeholder="0–5"/><Input label="Fecha de cata" type="date" value={draft.dateTasted} onChange={(event)=>set('dateTasted',event.target.value)}/><Input label="Precio pagado (€)" type="number" min="0" step="0.01" value={draft.price} onChange={(event)=>set('price',event.target.value)}/><Input label="Tienda o supermercado" value={draft.shop} onChange={(event)=>set('shop',event.target.value)}/><label className="sm:col-span-2 text-sm text-zinc-300">Notas de cata<textarea value={draft.notes} onChange={(event)=>set('notes',event.target.value)} rows={4} className="mt-1 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-white outline-none focus:border-rose-400"/></label><button type="button" onClick={()=>set('favorite',!draft.favorite)} aria-pressed={draft.favorite} className={`sm:col-span-2 flex items-center justify-center gap-2 rounded-xl border p-3 text-sm ${draft.favorite?'border-rose-400/40 bg-rose-500/10 text-rose-200':'border-white/10 text-zinc-400'}`}><Heart className={`h-4 w-4 ${draft.favorite?'fill-current':''}`}/>Guardar como favorito</button></div>}
  {error&&<p role="alert" className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{saving&&<div className="mt-4"><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-rose-400 transition-all" style={{width:`${progress}%`}}/></div><p className="mt-2 text-xs text-zinc-500">{progress<60?'Subiendo fotografía…':'Guardando vino y datos personales…'}</p></div>}
  <footer className="mt-6 flex gap-2">{step>1&&<button type="button" disabled={saving} onClick={()=>setStep((value)=>value-1)} className="flex h-12 items-center gap-2 rounded-xl border border-white/10 px-4 text-sm text-zinc-300"><ArrowLeft className="h-4 w-4"/>Atrás</button>}{step<3?<button type="button" disabled={processing} onClick={()=>setStep((value)=>value+1)} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-white font-semibold text-zinc-950">{step===1&&!file?'Continuar sin foto':'Continuar'}<ArrowRight className="h-4 w-4"/></button>:<button disabled={saving} className="flex h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-white font-semibold text-zinc-950 disabled:opacity-60">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}{saving?'Guardando…':'Guardar vino'}</button>}</footer></form></section></div>;
}
function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="text-sm text-zinc-300">{label}<input {...props} className="mt-1 h-11 w-full rounded-xl border border-white/10 bg-zinc-900 px-3 text-white outline-none placeholder:text-zinc-600 focus:border-rose-400"/></label>}
function normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function empty(value:string){return value.trim()||undefined} function number(value:string){const parsed=Number(value);return value.trim()&&Number.isFinite(parsed)?parsed:undefined} function list(value:string){return value.split(',').map((item)=>item.trim()).filter(Boolean)}
