'use client';

import Image from 'next/image';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Camera, Check, Images, Loader2, Sparkles, Trash2, X } from 'lucide-react';
import { createWine, listWineDenominationOptions, uploadWinePhoto } from '@/lib/wines/repository';
import { cleanBottlePhoto } from '@/lib/images/clean-bottle-photo';
import type { WineDenominationOption, WineItem, WineVisibility } from '@/types/wine';

type Draft = { name:string; winery:string; vintage:string; rating:string; supermarket:string; shop:string; price:string; country:string; region:string; denomination:string; grapes:string; notes:string; visibility:WineVisibility };
const initial:Draft={name:'',winery:'',vintage:String(new Date().getFullYear()),rating:'',supermarket:'',shop:'',price:'',country:'',region:'',denomination:'',grapes:'',notes:'',visibility:'private'};

export function WineCreateDialog({ open, onClose, onCreated, existingWines=[] }: { open:boolean; onClose:()=>void; onCreated:(wine:WineItem)=>void; existingWines?:WineItem[] }) {
  const closeRef=useRef<HTMLButtonElement>(null); const previewUrlsRef=useRef<string[]>([]); const[draft,setDraft]=useState(initial);const[files,setFiles]=useState<File[]>([]);const[previews,setPreviews]=useState<string[]>([]);const[denominations,setDenominations]=useState<WineDenominationOption[]>([]);const[processing,setProcessing]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);
  const suggestions=useMemo(()=>draft.name.trim().length<2?[]:existingWines.filter((wine)=>normalize(wine.name).includes(normalize(draft.name))).slice(0,4),[draft.name,existingWines]);
  useEffect(()=>{if(!open)return;closeRef.current?.focus();const escape=(event:KeyboardEvent)=>event.key==='Escape'&&onClose();document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape)},[onClose,open]);
  useEffect(()=>{if(!open)return;let active=true;void listWineDenominationOptions().then((options)=>{if(active)setDenominations(options)}).catch(()=>undefined);return()=>{active=false}},[open]);
  useEffect(()=>{previewUrlsRef.current=previews},[previews]);
  useEffect(()=>()=>previewUrlsRef.current.forEach((preview)=>URL.revokeObjectURL(preview)),[]);
  if(!open)return null;
  const set=(key:keyof Draft,value:string)=>setDraft((current)=>({...current,[key]:value}));
  function complete(wine:WineItem){setDraft((current)=>({...current,name:wine.name,winery:wine.winery??current.winery,vintage:wine.vintage?String(wine.vintage):current.vintage,country:wine.country??current.country,region:wine.region??current.region,denomination:wine.denomination??current.denomination,grapes:wine.grapes.join(', ')||current.grapes,supermarket:wine.supermarket??current.supermarket,shop:wine.shop??current.shop}));}
  async function choosePhotos(next:FileList){setProcessing(true);setError(null);try{const selected=Array.from(next).slice(0,5);const prepared=await Promise.all(selected.map((file,index)=>index===0?cleanBottlePhoto(file):file));previews.forEach((preview)=>URL.revokeObjectURL(preview));setFiles(prepared);setPreviews(prepared.map((file)=>URL.createObjectURL(file)))}catch(cause){setError(cause instanceof Error?cause.message:'No se pudieron preparar las imágenes.')}finally{setProcessing(false)}}
  function removePhoto(index:number){URL.revokeObjectURL(previews[index]);setFiles((current)=>current.filter((_,item)=>item!==index));setPreviews((current)=>current.filter((_,item)=>item!==index))}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError(null);try{if(!draft.name.trim())throw new Error('Escribe el nombre del vino.');const photoPaths=await Promise.all(files.map(uploadWinePhoto));const wine=await createWine({name:draft.name.trim(),winery:draft.winery.trim(),vintage:Number(draft.vintage)||new Date().getFullYear(),rating:Number(draft.rating)||0,supermarket:draft.supermarket.trim(),shop:draft.shop.trim()||undefined,price:draft.price?Number(draft.price):null,tasting_notes:draft.notes.trim(),image_url:photoPaths[0]??'',photo_paths:photoPaths,country:draft.country.trim()||undefined,region:draft.region.trim()||undefined,denomination:draft.denomination.trim()||undefined,grapes:draft.grapes.split(',').map((value)=>value.trim()).filter(Boolean),visibility:draft.visibility});onCreated(wine);setDraft(initial);setFiles([]);setPreviews([]);onClose()}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo guardar el vino.')}finally{setSaving(false)}}
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/75 backdrop-blur-sm sm:items-center sm:p-6"><section role="dialog" aria-modal="true" aria-labelledby="create-wine-title" className="max-h-[95dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] border border-white/10 bg-zinc-950 p-5 shadow-2xl sm:rounded-[2rem] sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-widest text-rose-300">Nueva botella</p><h2 id="create-wine-title" className="mt-1 text-2xl font-semibold text-white">Añadir a mi bodega</h2><p className="mt-1 text-xs text-zinc-500">Escribe el nombre y Atlas reutilizará datos que ya existen en tu bodega.</p></div><button ref={closeRef} onClick={onClose} aria-label="Cerrar" className="rounded-full p-2 text-zinc-400 hover:bg-white/10"><X className="h-5 w-5"/></button></div>
    <form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><div className="relative sm:col-span-2"><Input label="Nombre del vino" value={draft.name} onChange={(event)=>set('name',event.target.value)} autoFocus required placeholder="Empieza a escribir…"/>{suggestions.length>0&&<div className="mt-2 flex flex-wrap gap-2">{suggestions.map((wine)=><button key={wine.id} type="button" onClick={()=>complete(wine)} className="flex items-center gap-1.5 rounded-full border border-white/10 px-3 py-1.5 text-xs text-zinc-400 hover:bg-white/5 hover:text-white"><Sparkles className="h-3 w-3 text-rose-300"/>{wine.name}{wine.vintage?` · ${wine.vintage}`:''}</button>)}</div>}</div>
      <Input label="Bodega" value={draft.winery} onChange={(event)=>set('winery',event.target.value)} placeholder="Se completa al elegir un vino"/><Input label="Añada" type="number" min="1900" max="2100" value={draft.vintage} onChange={(event)=>set('vintage',event.target.value)}/><Input label="País" value={draft.country} onChange={(event)=>set('country',event.target.value)}/><Input label="Región" value={draft.region} onChange={(event)=>set('region',event.target.value)}/><Input label="Denominación" list="atlas-wine-denominations" value={draft.denomination} onChange={(event)=>{const value=event.target.value;set('denomination',value);const match=denominations.find((item)=>item.name===value);if(match&&!draft.country)set('country',match.country)}}/><datalist id="atlas-wine-denominations">{denominations.map((item)=><option key={`${item.country}-${item.name}`} value={item.name}>{item.classification} · {item.country}</option>)}</datalist><Input label="Uvas" value={draft.grapes} onChange={(event)=>set('grapes',event.target.value)} placeholder="Tempranillo, Garnacha…"/><Input label="Supermercado" value={draft.supermarket} onChange={(event)=>set('supermarket',event.target.value)}/><Input label="Tienda" value={draft.shop} onChange={(event)=>set('shop',event.target.value)}/><Input label="Precio (€)" type="number" min="0" step="0.01" value={draft.price} onChange={(event)=>set('price',event.target.value)}/><Input label="Valoración" type="number" min="0" max="5" step="0.5" value={draft.rating} onChange={(event)=>set('rating',event.target.value)} placeholder="Opcional"/>
      <label className="sm:col-span-2 text-sm text-zinc-300">Notas<textarea rows={3} value={draft.notes} onChange={(event)=>set('notes',event.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-white outline-none focus:border-rose-400"/></label>
      <div className="sm:col-span-2 rounded-2xl border border-dashed border-white/15 p-4"><div className="flex items-start justify-between gap-4"><div><strong className="flex items-center gap-2 text-sm font-medium text-white"><Images className="h-4 w-4 text-rose-300"/>Galería de la botella</strong><span className="mt-1 block text-xs leading-5 text-zinc-500">Sube hasta cinco fotos: frontal, etiqueta, contraetiqueta y el momento. La primera será la portada.</span></div><label className="shrink-0 cursor-pointer rounded-full bg-white px-3 py-2 text-xs font-semibold text-zinc-950 transition hover:bg-rose-50">{processing?'Preparando…':previews.length?'Cambiar':'Añadir fotos'}<input type="file" multiple accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event)=>{if(event.target.files?.length)void choosePhotos(event.target.files)}}/></label></div>{previews.length?<div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-5">{previews.map((preview,index)=><div key={preview} className="group relative aspect-square overflow-hidden rounded-xl border border-white/10 bg-white/[.03]"><Image src={preview} alt={`${draft.name||'Vino'} foto ${index+1}`} fill unoptimized className="object-contain p-2"/><span className="absolute bottom-1.5 left-1.5 rounded-full bg-black/65 px-2 py-1 text-[9px] font-medium text-white backdrop-blur">{index===0?'Portada':index+1}</span><button type="button" onClick={()=>removePhoto(index)} aria-label={`Eliminar foto ${index+1}`} className="absolute right-1.5 top-1.5 rounded-full bg-black/70 p-1.5 text-white opacity-0 transition group-hover:opacity-100 focus:opacity-100"><Trash2 className="h-3 w-3"/></button></div>)}</div>:<div className="mt-4 flex h-24 items-center justify-center rounded-xl bg-white/[.025] text-zinc-700"><Camera className="h-6 w-6"/></div>}</div>
      <label className="sm:col-span-2 text-sm text-zinc-300">Visibilidad<select value={draft.visibility} onChange={(event)=>set('visibility',event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-white/10 bg-zinc-900 px-3 text-white"><option value="private">Solo yo</option><option value="friends">Círculo</option><option value="public">Público</option></select></label>{error&&<p role="alert" className="sm:col-span-2 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={saving||processing} className="sm:col-span-2 inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-white font-semibold text-zinc-950 hover:bg-zinc-200 disabled:opacity-60">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Guardar vino</button></form></section></div>;
}
function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="text-sm text-zinc-300">{label}<input {...props} className="mt-1 h-11 w-full rounded-xl border border-white/10 bg-zinc-900 px-3 text-white outline-none placeholder:text-zinc-600 focus:border-rose-400"/></label>}
function normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
