'use client';

import { useCallback, useEffect, useState } from 'react';
import { Check, ExternalLink, Loader2, RefreshCw, ShieldAlert, X } from 'lucide-react';
import Image from 'next/image';
import { supabase } from '@/lib/supabase';

type Candidate = {
  id:string;proposed_image_url:string;source_name:string;source_url:string;source_license:string;confidence:number;
  wines:{name:string;winery:string|null;vintage:number|null}|null;
};

export default function WineEnrichmentAdminPage(){
  const[candidates,setCandidates]=useState<Candidate[]>([]),[loading,setLoading]=useState(true),[allowed,setAllowed]=useState<boolean|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);const{data:userData}=await supabase.auth.getUser();const isAdmin=userData.user?.app_metadata?.role==='admin';setAllowed(isAdmin);if(!isAdmin){setLoading(false);return;}const{data,error:queryError}=await supabase.from('wine_enrichment_candidates').select('id,proposed_image_url,source_name,source_url,source_license,confidence,wines(name,winery,vintage)').eq('status','pending').order('confidence',{ascending:false});if(queryError)setError(queryError.message);else setCandidates((data??[]) as unknown as Candidate[]);setLoading(false);},[]);
  useEffect(()=>{void load();},[load]);
  async function review(id:string,approved:boolean){setBusy(id);setError(null);const{error:reviewError}=await supabase.rpc('atlas_review_wine_enrichment',{candidate_id:id,approved});if(reviewError)setError(reviewError.message);else setCandidates((current)=>current.filter((item)=>item.id!==id));setBusy(null);}
  if(loading)return <State><Loader2 className="h-5 w-5 animate-spin"/>Cargando revisión…</State>;
  if(!allowed)return <State><ShieldAlert className="h-5 w-5"/>Esta sección está reservada a administradores.</State>;
  return <main className="min-h-screen bg-zinc-950 px-4 py-8 text-white"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-rose-300">Administración</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Revisión de fotografías</h1><p className="mt-2 text-sm text-zinc-400">Solo coincidencias reutilizables que requieren confirmación humana.</p></div><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-full border border-white/10 px-4 text-sm"><RefreshCw className="h-4 w-4"/>Actualizar</button></header>{error&&<p role="alert" className="mt-6 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<div className="mt-8 overflow-hidden rounded-2xl border border-white/10"><div className="hidden grid-cols-[2fr_140px_1.2fr_100px_180px] gap-4 border-b border-white/10 bg-white/[.04] px-5 py-3 text-xs uppercase tracking-wider text-zinc-500 md:grid"><span>Vino</span><span>Propuesta</span><span>Fuente</span><span>Confianza</span><span>Decisión</span></div>{candidates.map((candidate)=><article key={candidate.id} className="grid gap-4 border-b border-white/10 p-5 last:border-0 md:grid-cols-[2fr_140px_1.2fr_100px_180px] md:items-center"><div><h2 className="font-medium">{candidate.wines?.name??'Vino'}</h2><p className="mt-1 text-sm text-zinc-500">{[candidate.wines?.winery,candidate.wines?.vintage].filter(Boolean).join(' · ')||'Sin más datos'}</p></div><div className="relative aspect-[3/4] overflow-hidden rounded-xl bg-zinc-900"><Image unoptimized fill sizes="140px" src={candidate.proposed_image_url} alt={`Fotografía propuesta para ${candidate.wines?.name??'vino'}`} className="object-contain"/></div><div className="text-sm"><p>{candidate.source_name}</p><p className="mt-1 text-xs text-zinc-500">{candidate.source_license}</p><a href={candidate.source_url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs text-rose-300">Ver fuente<ExternalLink className="h-3 w-3"/></a></div><strong className="text-sm">{Math.round(candidate.confidence*100)}%</strong><div className="flex gap-2"><button disabled={busy===candidate.id} onClick={()=>void review(candidate.id,true)} aria-label="Aprobar fotografía" className="rounded-full bg-emerald-500/15 p-3 text-emerald-300 disabled:opacity-50"><Check className="h-4 w-4"/></button><button disabled={busy===candidate.id} onClick={()=>void review(candidate.id,false)} aria-label="Rechazar fotografía" className="rounded-full bg-red-500/15 p-3 text-red-300 disabled:opacity-50"><X className="h-4 w-4"/></button></div></article>)}{candidates.length===0&&<p className="p-12 text-center text-sm text-zinc-500">No hay coincidencias pendientes de revisión.</p>}</div></div></main>;
}
function State({children}:{children:React.ReactNode}){return <main className="flex min-h-[70vh] items-center justify-center gap-2 bg-zinc-950 px-4 text-sm text-zinc-400">{children}</main>;}
